apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
data:
  POSTGRES_DB: "todos"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  BACKEND_PORT: "3000"
  LOG_LEVEL: "info"
