apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: todo-app
  labels: { app: postgres }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-master
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: pg
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef: { name: app-secrets }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
